### ISSUE TITLE
`working-with-gedcom-files` missing from docs

### ISSUE THREAD

**Issue by MinchinWeb** [rory/gedcompy#13]
The documentation index (at https://raw.githubusercontent.com/rory/gedcompy/master/docs/index.rst ) references a section titled `working-with-gedcom-files`, but that file never seems to have been uploaded. As a result, the documentation says basically nothing about how to get information out of a GEDCOM file

**Comment by rory** [comment]
Thanks for noticing. I must have forgotten to finishe the docs!
