### ISSUE TITLE
NotImplementedError when xref_id comes before tag

### ISSUE THREAD

**Issue by jepst** [rory/gedcompy#14]
Ancestry.com produces Gedcoms with line like this:

0 @S-460522339@ SOUR
0 @R-995799905@ REPO

From my understanding of the [standard](http://homepages.rootsweb.ancestry.com/~pmcbride/gedcom/55gcch1.htm), this is valid. However, gedcompy raises NotImplementedError when it encounters lines like this (that is, when the xref comes before the tag).

**Comment by rory** [comment]
I think the problem was the `-` in the ID. Thanks for finding this. I've released v0.2.9 which should fix it.
